services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Netliva\SymfonyFastSearchBundle\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']

    Netliva\SymfonyFastSearchBundle\Services\:
        resource: '../../Services/'

    Netliva\SymfonyFastSearchBundle\Command\:
        resource: '../../Command/'
        tags: ['console.command']

    netliva_fastSearch_cacheClear:
        class: Netliva\SymfonyFastSearchBundle\EventListener\CacheClearEventListener
        tags:
            - { name: 'doctrine.event_listener', event: 'postPersist', connection: 'default' }
            - { name: 'doctrine.event_listener', event: 'postUpdate', connection: 'default' }
            - { name: 'doctrine.event_listener', event: 'preRemove', connection: 'default' }
