services:
    Netliva\SymfonyFastSearchBundle\Services\FastSearchServices:
        class: Netliva\SymfonyFastSearchBundle\Services\FastSearchServices
        public: false
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: twig.extension }

    netliva_fastSearchServices:
        alias: Netliva\SymfonyFastSearchBundle\Services\FastSearchServices
        public: true


    netliva_fastSearch_cacheClear:
        class: Netliva\SymfonyFastSearchBundle\EventListener\CacheClearEventListener
        arguments: [ @service_container]
        tags:
            - { name: 'doctrine.event_listener', event: 'postPersist', connection: 'default' }
            - { name: 'doctrine.event_listener', event: 'postUpdate', connection: 'default' }
            - { name: 'doctrine.event_listener', event: 'preRemove', connection: 'default' }
